---
title: "Holy cow!"
---

### I have a webpage!

The solution of problem 1 is [here](instacart_dashboard.html)

The solution of problem 2 is [here](https://liuweijie2132.shinyapps.io/problem_2/)

## Description of my dataset

There are 15 variables in this dataset:

order_id: order identifier

product_id: product identifier

add_to_cart_order: order in which each
product was added to cart

reordered: 1 if this prodcut has been ordered by this user in the past, 0 otherwise

user_id: customer identifier

eval_set: which evaluation set this order belongs in (Note that the data for use in this class is exclusively from the “train” eval_set)

order_number: the order sequence number for this user (1=first, n=nth)

order_dow: the day of the week on which the order was placed

order_hour_of_day: the hour of the day on which the order was placed

days_since_prior_order: days since the last order, capped at 30, NA if order_number=1

product_name: name of the product
aisle_id: aisle identifier

department_id: department identifier
aisle: the name of the aisle

department: the name of the department