---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)

instacart = read_csv("./data/instacart_train_data.csv.zip")


```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
instacart %>%
  count(department) %>%
  mutate(department = fct_reorder(department, n)) %>%
  plot_ly(x = ~department, y = ~n, color = ~department, type = "bar")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
instacart %>%
  mutate(departnemt = fct_reorder(department, order_hour_of_day)) %>%
  plot_ly(x = ~department, y = ~order_hour_of_day, color = ~department, type = "box")
```

### Chart C

```{r}
instacart %>%
  filter(order_dow == "4") %>%
  filter(user_id < 10000) %>%
  plot_ly(x = ~department, y = ~order_hour_of_day, color = ~department, type = "scatter", alpha = 0.1)
```

